apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: docker/example-voting-app-worker
        env:
        - name: REDIS_HOST
          value: redis-service
        - name: POSTGRES_HOST
          value: db-service
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: example
        command: ["sh", "-c", "sleep 20; ./worker"]
        resources:
          requests:
            cpu: 0.5
            memory: 128Mi
          limits:
            cpu: 0.9
            memory: 256Mi